FROM python:3.9

COPY ./src /src
COPY ./requirements.txt /requirements.txt

RUN pip install --no-cache-dir --upgrade -r /requirements.txt

WORKDIR /src
EXPOSE 9999

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9999", "--workers", "5", "--reload"]